// <auto-generated />
using System;
using Licitaciones.Domain.Enums;
using Licitaciones.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Licitaciones.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724011210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_licitacion", new[] { "Borrador", "Cerrada", "Publicada" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Licitaciones.Domain.Entities.Licitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoNormalizado")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_normalizado");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<EstadoLicitacion>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("estado_licitacion")
                        .HasDefaultValue(EstadoLicitacion.Borrador)
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<decimal>("PresupuestoEstimadoCrc")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_estimado_crc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("titulo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_licitaciones");

                    b.HasIndex("CodigoNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_licitaciones_codigo_normalizado")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_licitaciones_deleted_at");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_licitaciones_estado");

                    b.HasIndex("FechaCierre")
                        .HasDatabaseName("ix_licitaciones_fecha_cierre");

                    b.ToTable("licitaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_licitaciones_presupuesto_positivo", "presupuesto_estimado_crc > 0");

                            t.HasCheckConstraint("ck_licitaciones_titulo_no_vacio", "length(trim(titulo)) > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entities.NivelAprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Aprobador")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("aprobador");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("MontoMaximoCrc")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_maximo_crc");

                    b.Property<decimal>("MontoMinimoCrc")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_minimo_crc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_niveles_aprobacion");

                    b.ToTable("niveles_aprobacion", null, t =>
                        {
                            t.HasCheckConstraint("ck_niveles_aprobador_no_vacio", "length(trim(aprobador)) > 0");

                            t.HasCheckConstraint("ck_niveles_monto_maximo_mayor_minimo", "monto_maximo_crc IS NULL OR monto_maximo_crc > monto_minimo_crc");

                            t.HasCheckConstraint("ck_niveles_monto_minimo_no_negativo", "monto_minimo_crc >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Aprobador = "Encargado de área",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MontoMaximoCrc = 999999.99m,
                            MontoMinimoCrc = 0.01m,
                            RowVersion = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Aprobador = "Gerencia",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MontoMaximoCrc = 9999999.99m,
                            MontoMinimoCrc = 1000000m,
                            RowVersion = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Aprobador = "Junta Directiva",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MontoMinimoCrc = 10000000m,
                            RowVersion = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entities.Oferta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LicitacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("licitacion_id");

                    b.Property<decimal>("MontoOfertadoCrc")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_ofertado_crc");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_ofertas");

                    b.HasIndex("LicitacionId")
                        .HasDatabaseName("ix_ofertas_licitacion_id");

                    b.HasIndex("ProveedorId")
                        .HasDatabaseName("ix_ofertas_proveedor_id");

                    b.HasIndex("LicitacionId", "ProveedorId")
                        .IsUnique()
                        .HasDatabaseName("ux_ofertas_licitacion_proveedor");

                    b.HasIndex("LicitacionId", "MontoOfertadoCrc", "FechaRegistro")
                        .HasDatabaseName("ix_ofertas_licitacion_monto_fecha");

                    b.ToTable("ofertas", null, t =>
                        {
                            t.HasCheckConstraint("ck_ofertas_monto_positivo", "monto_ofertado_crc > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_normalizado");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_proveedores");

                    b.HasIndex("EliminadoEn")
                        .HasDatabaseName("ix_proveedores_deleted_at");

                    b.HasIndex("NombreNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_proveedores_nombre_normalizado")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("proveedores", null, t =>
                        {
                            t.HasCheckConstraint("ck_proveedores_nombre_caracteres", "nombre ~ '^[[:alnum:][:space:].,()]+$'");

                            t.HasCheckConstraint("ck_proveedores_nombre_no_vacio", "length(trim(nombre)) > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entities.TipoCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("activo");

                    b.Property<decimal>("CrcPorUsd")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("crc_por_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("FechaVigencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vigencia");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_tipos_cambio");

                    b.HasIndex("Activo")
                        .IsUnique()
                        .HasDatabaseName("ux_tipos_cambio_unico_activo")
                        .HasFilter("activo");

                    b.HasIndex("FechaVigencia")
                        .IsDescending()
                        .HasDatabaseName("ix_tipos_cambio_fecha_vigencia");

                    b.ToTable("tipos_cambio", null, t =>
                        {
                            t.HasCheckConstraint("ck_tipos_cambio_valor_positivo", "crc_por_usd > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            CrcPorUsd = 520.000000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaVigencia = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RowVersion = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entities.Oferta", b =>
                {
                    b.HasOne("Licitaciones.Domain.Entities.Licitacion", null)
                        .WithMany()
                        .HasForeignKey("LicitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_licitacion");

                    b.HasOne("Licitaciones.Domain.Entities.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
