apiVersion: v1
kind: Secret
metadata:
  name: licitaciones-secrets
  namespace: licitaciones
type: Opaque
stringData:
  POSTGRES_USER: replace-before-deploy
  POSTGRES_PASSWORD: replace-before-deploy
  POSTGRES_DB: licitaciones
  ConnectionStrings__DefaultConnection: Host=licitaciones-db;Port=5432;Database=licitaciones;Username=replace-before-deploy;Password=replace-before-deploy
