apiVersion: v1
kind: Service
metadata:
  name: licitaciones-db
  namespace: licitaciones
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: licitaciones-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
